from flask import Flask, render_template_string, request, redirect, jsonify
import requests
import urllib.parse
import re
import time
import random
import threading
import json
import os
from datetime import datetime
from html import escape
from html.parser import HTMLParser

# ============================================================
# CONFIGURATION
# ============================================================

app = Flask(__name__)

HARMONY_URL = "http://harmony:8000"
HARMONY_BROWSER_URL = os.getenv("HARMONY_BROWSER_URL", "http://localhost:8001")
DEEZER_API = "https://api.deezer.com"
MUSICBRAINZ_API = "https://musicbrainz.org/ws/2"

MUSICBRAINZ_SEED_URL = "https://musicbrainz.org/release/add?skip_confirmation=1"


class HiddenInputParser(HTMLParser):
    """Extract hidden form inputs from Harmony's release-seeder form."""

    def __init__(self):
        super().__init__()
        self.in_seed_form = False
        self.seed_action = None
        self.fields = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)

        if tag.lower() == "form":
            if attrs.get("name") == "release-seeder":
                self.in_seed_form = True
                self.seed_action = attrs.get("action")

        elif tag.lower() == "input" and self.in_seed_form:
            if attrs.get("type", "").lower() == "hidden":
                name = attrs.get("name")
                value = attrs.get("value", "")

                if name:
                    self.fields.append((name, value))

    def handle_endtag(self, tag):
        if tag.lower() == "form" and self.in_seed_form:
            self.in_seed_form = False


def get_harmony_musicbrainz_seed(deezer_url):
    """
    Fetch Harmony's release page and extract the exact MusicBrainz
    release-seeder form generated by Harmony.
    """

    try:
        response = requests.get(
            f"{HARMONY_URL}/release",
            params={
                "url": deezer_url,
                "category": "all",
            },
            timeout=30,
        )

        response.raise_for_status()

    except requests.RequestException as exc:
        return None, f"Harmony request failed: {exc}"

    parser = HiddenInputParser()
    parser.feed(response.text)

    if not parser.fields:
        return None, (
            "Harmony did not return a release-seeder form. "
            "The release may not have been resolved by Harmony."
        )

    if not parser.seed_action:
        return None, "Harmony release-seeder form has no target action."

    if not parser.seed_action.startswith(
        "https://musicbrainz.org/release/add"
    ):
        return None, (
            "Harmony returned an unexpected MusicBrainz seed target: "
            f"{parser.seed_action}"
        )

    return {
        "action": parser.seed_action,
        "fields": parser.fields,
    }, None


def build_musicbrainz_seed_page(seed, deezer_url, album_id):
    """
    Build a browser page that automatically POSTs Harmony's exact
    seed fields to the MusicBrainz Release Editor.

    The final MusicBrainz edit is NOT submitted automatically.
    MusicBrainz displays the Release Editor for user review.
    """

    rewritten_fields = []

    for name, value in seed["fields"]:
        if isinstance(value, str):
            value = value.replace(
                "http://localhost:8000",
                HARMONY_BROWSER_URL,
            ).replace(
                "http://harmony:8000",
                HARMONY_BROWSER_URL,
            )

        rewritten_fields.append((name, value))

    html_parts = [
        "<!doctype html>",
        "<html>",
        "<head>",
        '<meta charset="utf-8">',
        "<title>Auto-Stage Import</title>",
        """
        <style>
            body {
                font-family: system-ui, sans-serif;
                max-width: 760px;
                margin: 60px auto;
                padding: 0 20px;
                line-height: 1.5;
            }
            .box {
                border: 1px solid #ccc;
                border-radius: 10px;
                padding: 24px;
            }
            .status {
                font-size: 18px;
                font-weight: 600;
            }
            button {
                padding: 10px 18px;
                font-size: 16px;
                cursor: pointer;
            }
        </style>
        """,
        "</head>",
        "<body>",
        '<div class="box">',
        "<h1>Auto-Stage Import</h1>",
        f"<p>Preparing MusicBrainz Release Editor for album "
        f"<strong>{escape(str(album_id))}</strong>.</p>",
        '<p class="status">MusicBrainz Release Editor is ready for review.</p>',
        """
        <form id="seed-form"
              action="https://musicbrainz.org/release/add?skip_confirmation=1"
              method="post">
        """,
    ]

    for name, value in rewritten_fields:
        html_parts.append(
            f'<input type="hidden" name="{escape(name, quote=True)}" '
            f'value="{escape(str(value), quote=True)}">'
        )

    html_parts.extend([
        "</form>",
        """
        <noscript>
            <p>JavaScript is disabled. Click the button below.</p>
            <button type="submit" form="seed-form">
                Continue to MusicBrainz
            </button>
        </noscript>
        """,
        "</div>",
        """
        <script>
            window.setTimeout(function() {
                document.getElementById("seed-form").submit();
            }, 150);
        </script>
        """,
        "</body>",
        "</html>",
    ])

    return "\n".join(html_parts)


def create_auto_stage_seed(deezer_url):
    """
    Perform the final UPC duplicate check, then obtain Harmony's
    exact MusicBrainz seed.

    Returns:
        (html, status_code, message)
    """

    parsed = urllib.parse.urlparse(deezer_url)
    query = urllib.parse.parse_qs(parsed.query)

    album_id = None

    match = re.search(r"/album/(\d+)", parsed.path)
    if match:
        album_id = match.group(1)

    if not album_id and query.get("id"):
        album_id = query["id"][0]

    if not album_id:
        return None, 400, "Could not determine Deezer album ID."

    # --------------------------------------------------------
    # Get UPC again immediately before staging.
    # --------------------------------------------------------
    upc = get_deezer_album_upc(album_id)

    if not upc:
        return None, 400, (
            f"Could not determine UPC for Deezer album {album_id}."
        )

    # --------------------------------------------------------
    # FINAL MusicBrainz duplicate check.
    #
    # True  = exists
    # False = missing
    # None  = lookup failure
    # --------------------------------------------------------
    mb_exists = check_musicbrainz_barcode(upc)

    if mb_exists is True:
        return None, 409, (
            f"MusicBrainz already contains a release with UPC {upc}."
        )

    if mb_exists is None:
        return None, 502, (
            f"MusicBrainz UPC check failed for {upc}. "
            "Nothing was staged."
        )

    # --------------------------------------------------------
    # Only now ask Harmony to generate the exact seed.
    # --------------------------------------------------------
    seed, error = get_harmony_musicbrainz_seed(deezer_url)

    if error:
        return None, 502, error

    # --------------------------------------------------------
    # Safety check: make sure Harmony's seed contains the same
    # UPC that we just verified as missing.
    # --------------------------------------------------------
    seed_barcodes = [
        value
        for name, value in seed["fields"]
        if name == "barcode"
    ]

    if upc not in seed_barcodes:
        return None, 502, (
            "Harmony's generated seed does not contain the expected "
            f"UPC {upc}. Nothing was staged."
        )

    # --------------------------------------------------------
    # Record the action only after:
    #   1. final duplicate check succeeded
    #   2. Harmony successfully generated the seed
    # --------------------------------------------------------
    album_data = get_deezer_album(album_id)

    artist_name = ""
    artist_id = ""
    album_title = ""

    if album_data:
        album_title = str(
            album_data.get("title", "")
        ).strip()

        artist_data = album_data.get("artist") or {}

        artist_name = str(
            artist_data.get("name", "")
        ).strip()

        artist_id = str(
            artist_data.get("id", "")
        ).strip()

    record_import(
        artist_name=artist_name,
        artist_id=artist_id,
        album_id=album_id,
        album_title=album_title,
        upc=upc,
    )

    return (
        build_musicbrainz_seed_page(
            seed,
            deezer_url,
            album_id,
        ),
        200,
        None,
    )


# IMPORTANT:
# Replace this with a real email address.
MB_USER_AGENT = os.getenv("MB_USER_AGENT", "MBAutomationScript/1.2 (https://github.com/example/musicbrainz-automation)")

# MusicBrainz requires requests to be spaced out.
MB_MIN_INTERVAL = 1.5

# Retry transient MusicBrainz failures.
MB_MAX_RETRIES = 5
RETRY_STATUS_CODES = {429, 500, 502, 503, 504}

# Persistent import statistics.
IMPORT_STATS_FILE = "/data/import_stats.json"


# ============================================================
# GLOBAL STATE
# ============================================================

session = requests.Session()

session.headers.update({
    "User-Agent": MB_USER_AGENT,
    "Accept": "application/json"
})


def reset_http_session():
    """
    Close the current HTTP session and create a fresh one.

    This helps recover from stale or broken persistent HTTPS
    connections without changing the MusicBrainz retry behavior.
    """

    global session

    try:
        session.close()
    except Exception:
        pass

    session = requests.Session()

    session.headers.update({
        "User-Agent": MB_USER_AGENT,
        "Accept": "application/json"
    })


last_musicbrainz_request = 0

current_data = {
    "artist_query": "Daft Punk",
    "resolved_name": "Daft Punk",
    "artist_id": "27",
    "albums_count": 0,
    "checked_count": 0,
    "existing": 0,
    "errors": 0,
    "no_upc": 0,
    "missing_items": [],
    "status": "Ready. Enter an Artist Name or ID number to search.",
    "candidates": []
}

# Persistent last-scan results.
LAST_SCAN_FILE = "/opt/mb-automation/last_scan.json"


def save_last_scan():
    """
    Persist the current completed scan so the dashboard can
    restore it after the browser or dashboard is restarted.
    """

    try:

        temp_file = (
            LAST_SCAN_FILE +
            ".tmp"
        )

        with open(
            temp_file,
            "w",
            encoding="utf-8"
        ) as file:

            json.dump(
                current_data,
                file,
                indent=2
            )

        os.replace(
            temp_file,
            LAST_SCAN_FILE
        )

    except Exception as exc:

        print(
            f"WARNING: Could not save last scan: {exc}"
        )


def load_last_scan():
    """
    Restore the most recent completed scan from disk.
    """

    try:

        if not os.path.exists(
            LAST_SCAN_FILE
        ):
            return None

        with open(
            LAST_SCAN_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            data = json.load(file)

        if not isinstance(
            data,
            dict
        ):
            return None

        return data

    except Exception as exc:

        print(
            f"WARNING: Could not load last scan: {exc}"
        )

        return None


def clear_last_scan():
    """
    Remove the persisted last-scan results.
    """

    try:

        if os.path.exists(
            LAST_SCAN_FILE
        ):
            os.remove(
                LAST_SCAN_FILE
            )

    except Exception as exc:

        print(
            f"WARNING: Could not clear last scan: {exc}"
        )


# Live scan output
scan_log = []
scan_running = False
scan_cancel_requested = False
scan_lock = threading.Lock()

# Restore the most recent completed scan, if one exists.
_saved_last_scan = load_last_scan()

if _saved_last_scan:
    current_data = _saved_last_scan

# Tracks imports sent during the current scan.
current_scan_import_count = 0
current_scan_import_keys = set()

# Persistent import statistics lock.
import_stats_lock = threading.Lock()


# ============================================================
# PERSISTENT IMPORT STATISTICS
# ============================================================

def load_import_stats():
    """
    Load persistent import statistics.

    The file is intentionally simple JSON so it is easy to inspect
    or back up manually.
    """

    default_stats = {
        "total_unique_sent": 0,
        "total_actions": 0,
        "imports": []
    }

    try:

        if not os.path.exists(IMPORT_STATS_FILE):
            return default_stats

        with open(
            IMPORT_STATS_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            data = json.load(file)

        if not isinstance(data, dict):
            return default_stats

        data.setdefault(
            "total_unique_sent",
            0
        )

        data.setdefault(
            "total_actions",
            0
        )

        data.setdefault(
            "imports",
            []
        )

        return data

    except Exception:

        return default_stats


def save_import_stats(stats):
    """
    Atomically save persistent import statistics.
    """

    directory = os.path.dirname(
        IMPORT_STATS_FILE
    )

    os.makedirs(
        directory,
        exist_ok=True
    )

    temp_file = (
        f"{IMPORT_STATS_FILE}.tmp"
    )

    with open(
        temp_file,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            stats,
            file,
            indent=2
        )

    os.replace(
        temp_file,
        IMPORT_STATS_FILE
    )


def get_import_stats():
    """
    Return a copy of the persistent statistics.
    """

    with import_stats_lock:

        stats = load_import_stats()

        return {
            "total_unique_sent": stats.get(
                "total_unique_sent",
                0
            ),
            "total_actions": stats.get(
                "total_actions",
                0
            ),
            "imports": list(
                stats.get(
                    "imports",
                    []
                )
            )
        }


def record_import(
    artist_name,
    artist_id,
    album_id,
    album_title,
    upc
):
    """
    Record that a release was successfully staged for MusicBrainz.

    The lifetime unique count is deduplicated by Deezer album ID.

    total_actions counts every successful Auto-Stage action.

    Returns:

        {
            "recorded": True/False,
            "unique": True/False,
            "total_unique_sent": N,
            "total_actions": N
        }
    """

    global current_scan_import_count

    unique_key = (
        f"deezer_album:{album_id}"
        if album_id
        else f"upc:{upc}"
    )

    with import_stats_lock:

        stats = load_import_stats()

        imports = stats.setdefault(
            "imports",
            []
        )

        now = datetime.now().astimezone().isoformat(
            timespec="seconds"
        )

        stats["total_actions"] = (
            stats.get(
                "total_actions",
                0
            ) + 1
        )

        already_sent = any(
            item.get("unique_key") == unique_key
            for item in imports
        )

        if not already_sent:

            stats["total_unique_sent"] = (
                stats.get(
                    "total_unique_sent",
                    0
                ) + 1
            )

            imports.append({
                "unique_key": unique_key,
                "timestamp": now,
                "artist_name": artist_name,
                "artist_id": str(artist_id),
                "album_id": str(album_id),
                "album_title": album_title,
                "upc": upc
            })

            unique = True

        else:

            unique = False

        save_import_stats(
            stats
        )

    if unique:

        with scan_lock:

            if unique_key not in current_scan_import_keys:

                current_scan_import_keys.add(
                    unique_key
                )

                current_scan_import_count += 1

    return {
        "recorded": True,
        "unique": unique,
        "total_unique_sent": stats.get(
            "total_unique_sent",
            0
        ),
        "total_actions": stats.get(
            "total_actions",
            0
        )
    }


# ============================================================
# LIVE SCAN LOGGING
# ============================================================

def clear_scan_log():
    global scan_log

    with scan_lock:
        scan_log.clear()


def add_scan_log(message):
    global scan_log

    with scan_lock:
        scan_log.append(message)


def set_scan_running(value):
    global scan_running

    with scan_lock:
        scan_running = value


def is_scan_running():
    with scan_lock:
        return scan_running


def request_scan_cancel():
    global scan_cancel_requested

    with scan_lock:
        scan_cancel_requested = True


def is_scan_cancel_requested():
    with scan_lock:
        return scan_cancel_requested


def reset_scan_cancel():
    global scan_cancel_requested

    with scan_lock:
        scan_cancel_requested = False


def reset_scan_import_counter():
    global current_scan_import_count
    global current_scan_import_keys

    with scan_lock:

        current_scan_import_count = 0
        current_scan_import_keys = set()


def get_scan_import_count():

    with scan_lock:

        return current_scan_import_count


# ============================================================
# MUSICBRAINZ RATE LIMITING
# ============================================================

def wait_for_musicbrainz():
    global last_musicbrainz_request

    elapsed = (
        time.monotonic()
        - last_musicbrainz_request
    )

    if elapsed < MB_MIN_INTERVAL:

        time.sleep(
            MB_MIN_INTERVAL - elapsed
        )

    last_musicbrainz_request = (
        time.monotonic()
    )


# ============================================================
# DEEZER
# ============================================================

def search_deezer_artists(query_text):
    """
    Query Deezer and return up to 3 candidate artists.
    """

    url = (
        f"{DEEZER_API}/search/artist"
    )

    try:

        response = session.get(
            url,
            params={
                "q": query_text,
                "limit": 3
            },
            timeout=30
        )

        response.raise_for_status()

        return response.json().get(
            "data",
            []
        )

    except Exception:

        return []


def get_deezer_albums(artist_id):
    """
    Retrieve the complete Deezer album catalog for an artist.
    """

    albums = []

    url = (
        f"{DEEZER_API}/artist/"
        f"{artist_id}/albums"
    )

    while url:

        try:

            response = session.get(
                url,
                timeout=30
            )

            response.raise_for_status()

            data = response.json()

            albums.extend(
                data.get(
                    "data",
                    []
                )
            )

            url = data.get(
                "next"
            )

        except Exception:

            break

    return albums


def get_deezer_album_upc(album_id):
    """
    Retrieve the UPC/barcode for a Deezer album.
    """

    url = (
        f"{DEEZER_API}/album/"
        f"{album_id}"
    )

    try:

        response = session.get(
            url,
            timeout=30
        )

        response.raise_for_status()

        return response.json().get(
            "upc"
        )

    except Exception:

        return None


def get_deezer_album(album_id):
    """
    Retrieve the complete Deezer album record.
    """

    url = (
        f"{DEEZER_API}/album/"
        f"{album_id}"
    )

    try:

        response = session.get(
            url,
            timeout=30
        )

        response.raise_for_status()

        return response.json()

    except Exception:

        return None


# ============================================================
# MUSICBRAINZ
# ============================================================

def check_musicbrainz_barcode(
    barcode,
    album_title=None,
    artist_name=None
):
    """
    Check MusicBrainz for an existing release.

    Matching order:
        1. Exact barcode match
        2. Artist + album title fallback

    Returns:
        True  = release found
        False = successful lookup, release not found
        None  = lookup failed after retries
    """

    def normalize_text(value):

        if not value:
            return ""

        value = str(
            value
        ).lower()

        value = re.sub(
            r"[^a-z0-9]+",
            " ",
            value
        )

        return " ".join(
            value.split()
        )

    def musicbrainz_request(
        params
    ):

        url = (
            f"{MUSICBRAINZ_API}/release/"
        )

        for attempt in range(
            1,
            MB_MAX_RETRIES + 1
        ):

            wait_for_musicbrainz()

            try:

                response = session.get(
                    url,
                    params=params,
                    timeout=30
                )

                if response.status_code == 200:

                    return response.json()

                if response.status_code in RETRY_STATUS_CODES:

                    delay = (
                        min(
                            30,
                            2 ** attempt
                        )
                        + random.uniform(
                            0,
                            1
                        )
                    )

                    add_scan_log(
                        f"    MusicBrainz returned HTTP "
                        f"{response.status_code}. "
                        f"Retrying in {delay:.1f}s "
                        f"(attempt {attempt}/"
                        f"{MB_MAX_RETRIES})..."
                    )

                    if attempt < MB_MAX_RETRIES:

                        time.sleep(
                            delay
                        )

                        continue

                    return None

                add_scan_log(
                    f"    MusicBrainz returned HTTP "
                    f"{response.status_code}. "
                    f"Not retrying."
                )

                return None

            except requests.RequestException as exc:

                reset_http_session()

                if attempt >= MB_MAX_RETRIES:

                    add_scan_log(
                        f"    MusicBrainz request failed "
                        f"after {MB_MAX_RETRIES} attempts: "
                        f"{exc}"
                    )

                    return None

                delay = (
                    min(
                        30,
                        2 ** attempt
                    )
                    + random.uniform(
                        0,
                        1
                    )
                )

                add_scan_log(
                    f"    MusicBrainz request error: "
                    f"{exc}. "
                    f"Retrying in {delay:.1f}s "
                    f"(attempt {attempt}/"
                    f"{MB_MAX_RETRIES})..."
                )

                time.sleep(
                    delay
                )

        return None

    # --------------------------------------------------------
    # First: exact barcode lookup
    # --------------------------------------------------------

    if barcode:

        barcode_data = musicbrainz_request({
            "query": f"barcode:{barcode}",
            "fmt": "json",
            "limit": 1
        })

        if barcode_data is None:

            return None

        releases = barcode_data.get(
            "releases",
            []
        )

        if releases:

            return True

    # --------------------------------------------------------
    # Second: artist + album title fallback
    # --------------------------------------------------------

    if not album_title or not artist_name:

        return False

    artist_normalized = normalize_text(
        artist_name
    )

    title_normalized = normalize_text(
        album_title
    )

    if not artist_normalized or not title_normalized:

        return False

    fallback_query = (
        f'artist:"{artist_name}" '
        f'release:"{album_title}"'
    )

    add_scan_log(
        "    UPC not found. "
        "Trying artist/title match..."
    )

    fallback_data = musicbrainz_request({
        "query": fallback_query,
        "fmt": "json",
        "limit": 10
    })

    if fallback_data is None:

        return None

    fallback_releases = fallback_data.get(
        "releases",
        []
    )

    for release in fallback_releases:

        release_title = normalize_text(
            release.get(
                "title",
                ""
            )
        )

        if release_title != title_normalized:

            continue

        release_artist_match = False

        for artist_credit in release.get(
            "artist-credit",
            []
        ):

            artist = artist_credit.get(
                "artist",
                {}
            )

            candidate_artist = normalize_text(
                artist.get(
                    "name",
                    ""
                )
            )

            if candidate_artist == artist_normalized:

                release_artist_match = True
                break

        if release_artist_match:

            return True

    return False



# ============================================================
# SCAN
# ============================================================

def perform_scan(
    artist_id,
    artist_name,
    artist_query,
    expected_releases=None
):
    """
    Perform the complete Deezer -> UPC -> MusicBrainz scan.

    This runs in a background thread so the web page remains
    responsive and can display live progress.
    """

    global current_data

    set_scan_running(True)
    clear_scan_log()
    reset_scan_import_counter()

    try:

        add_scan_log(
            f'Starting scan for "{artist_name}" '
            f"(Deezer ID: {artist_id})"
        )

        if expected_releases is not None:

            add_scan_log(
                f"Expected releases to scan: "
                f"{expected_releases}"
            )

        add_scan_log("")

        add_scan_log(
            "Retrieving album catalog from Deezer..."
        )

        albums = get_deezer_albums(
            artist_id
        )

        if not albums:

            add_scan_log("")

            add_scan_log(
                "ERROR: No album catalog entries "
                "were found."
            )

            current_data = {
                "artist_query": artist_query,
                "resolved_name": artist_name,
                "artist_id": artist_id,
                "albums_count": 0,
                "checked_count": 0,
                "existing": 0,
                "errors": 0,
                "no_upc": 0,
                "missing_items": [],
                "status": (
                    "No album catalog entries found "
                    "for verified artist."
                ),
                "candidates": []
            }

            return

        total_albums = len(
            albums
        )

        add_scan_log(
            f"Retrieved {total_albums} album entries "
            f"from Deezer."
        )

        add_scan_log("")

        add_scan_log(
            "Beginning UPC and MusicBrainz checks..."
        )

        add_scan_log("")

        existing = 0
        errors = 0
        no_upc = 0
        checked_count = 0

        missing_items = []

        # ----------------------------------------------------
        # Check for cancellation before each album.
        # ----------------------------------------------------
        for index, album in enumerate(
            albums,
            start=1
        ):

            if is_scan_cancel_requested():

                add_scan_log("")

                add_scan_log(
                    "============================================================"
                )

                add_scan_log(
                    "SCAN CANCELLED"
                )

                add_scan_log(
                    f"Stopped before album {index} "
                    f"of {total_albums}."
                )

                add_scan_log(
                    "============================================================"
                )

                current_data = {
                    "artist_query": artist_query,
                    "resolved_name": artist_name,
                    "artist_id": artist_id,
                    "albums_count": total_albums,
                    "checked_count": checked_count,
                    "existing": existing,
                    "errors": errors,
                    "no_upc": no_upc,
                    "missing_items": missing_items,
                    "status": (
                        f'Analysis of "{artist_name}" '
                        f"was cancelled."
                    ),
                    "candidates": []
                }

                return

            album_id = album.get(
                "id"
            )

            title = album.get(
                "title",
                "Unknown Title"
            )

            cover_url = album.get(
                "cover_medium",
                ""
            )

            add_scan_log(
                f'[{index}/{total_albums}] '
                f'Checking "{title}"...'
            )

            # Retrieve UPC
            add_scan_log(
                "    Retrieving UPC from Deezer..."
            )

            upc = get_deezer_album_upc(
                album_id
            )

            if not upc:

                no_upc += 1

                add_scan_log(
                    "    No UPC found. "
                    "Skipping MusicBrainz lookup."
                )

                add_scan_log("")

                continue

            checked_count += 1

            add_scan_log(
                f"    UPC: {upc}"
            )

            # MusicBrainz lookup
            add_scan_log(
                "    Checking MusicBrainz..."
            )

            mb_result = check_musicbrainz_barcode(
                upc,
                album_title=title,
                artist_name=artist_name
            )

            # Found
            if mb_result is True:

                existing += 1

                add_scan_log(
                    "    MusicBrainz: FOUND"
                )

            # Missing
            elif mb_result is False:

                add_scan_log(
                    "    MusicBrainz: MISSING"
                )

                deezer_link = (
                    f"https://deezer.com/album/"
                    f"{album_id}"
                )

                encoded_url = (
                    urllib.parse.quote(
                        deezer_link,
                        safe=""
                    )
                )

                harmony_url = (
                    f"{HARMONY_URL}/release"
                    f"?url={encoded_url}"
                )

                spaced_url = re.sub(
                    r"([:/?.=&])",
                    r" \1",
                    harmony_url
                )

                missing_items.append({
                    "title": title,
                    "upc": upc,
                    "cover": cover_url,
                    "album_id": album_id,
                    "harmony_link": (
                        f"/mb-seed?url="
                        f"{urllib.parse.quote(deezer_link, safe='')}"
                    ),
                    "display_url": spaced_url
                })

            # Lookup error
            else:

                errors += 1

                add_scan_log(
                    "    MusicBrainz: LOOKUP ERROR"
                )

            add_scan_log("")

        # Final summary
        add_scan_log(
            "============================================================"
        )

        add_scan_log(
            "SCAN COMPLETE"
        )

        add_scan_log(
            f"Albums retrieved: {total_albums}"
        )

        add_scan_log(
            f"Albums checked by UPC: {checked_count}"
        )

        add_scan_log(
            f"Albums without UPC: {no_upc}"
        )

        add_scan_log(
            f"Existing on MusicBrainz: {existing}"
        )

        add_scan_log(
            f"Confirmed missing: "
            f"{len(missing_items)}"
        )

        add_scan_log(
            f"Lookup errors: {errors}"
        )

        add_scan_log(
            "============================================================"
        )

        current_data = {
            "artist_query": artist_query,
            "resolved_name": artist_name,
            "artist_id": artist_id,
            "albums_count": total_albums,
            "checked_count": checked_count,
            "existing": existing,
            "errors": errors,
            "no_upc": no_upc,
            "missing_items": missing_items,
            "status": (
                f'Scan completed for "{artist_name}"! '
                f"Discovered {len(missing_items)} "
                f"missing library releases."
            ),
            "candidates": []
        }

        save_last_scan()

    except Exception as exc:

        add_scan_log("")

        add_scan_log(
            "============================================================"
        )

        add_scan_log(
            f"FATAL ERROR: {exc}"
        )

        add_scan_log(
            "============================================================"
        )

        current_data = {
            "artist_query": artist_query,
            "resolved_name": artist_name,
            "artist_id": artist_id,
            "albums_count": 0,
            "checked_count": 0,
            "existing": 0,
            "errors": 1,
            "no_upc": 0,
            "missing_items": [],
            "status": f"Scan failed: {exc}",
            "candidates": []
        }

    finally:

        set_scan_running(False)


# ============================================================
# HTML
# ============================================================

HTML = """
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >

    <title>Auto-Stage Import Console</title>

    <style>

        body {
            font-family: Arial, sans-serif;
            background: #f5f7fa;
            color: #1a202c;
            margin: 0;
            padding: 30px;
        }

        .container {
            max-width: 1200px;
            margin: auto;
        }

        h1 {
            margin-bottom: 20px;
        }

        .search-box {
            background: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 1px 4px rgba(0,0,0,0.08);
        }

        input[type="text"] {
            width: 70%;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #cbd5e0;
            border-radius: 5px;
        }

        button {
            padding: 10px 16px;
            font-size: 15px;
            cursor: pointer;
            border: none;
            border-radius: 5px;
            background: #3182ce;
            color: white;
        }

        button:hover {
            background: #2b6cb0;
        }

        button:disabled {
            background: #a0aec0;
            cursor: not-allowed;
        }

        .status {
            background: #ebf8ff;
            border: 1px solid #90cdf4;
            color: #2a4365;
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 20px;
        }

        .scan-output {
            display: none;
            background: #1a202c;
            color: #e2e8f0;
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 20px;
            font-family: monospace;
            font-size: 12px;
            line-height: 1.6;
            max-height: 400px;
            overflow-y: auto;
            white-space: pre-wrap;
            border: 1px solid #2d3748;
        }

        .scan-output-header {
            color: #90cdf4;
            font-family: Arial, sans-serif;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .candidate-grid {
            display: grid;
            grid-template-columns: repeat(
                auto-fit,
                minmax(250px, 1fr)
            );
            gap: 20px;
            margin-bottom: 30px;
        }

        .candidate {
            background: white;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 1px 4px rgba(0,0,0,0.08);
        }

        .candidate img {
            width: 120px;
            height: 120px;
            object-fit: cover;
            border-radius: 6px;
            margin-bottom: 10px;
        }

        .candidate h3 {
            margin: 5px 0;
        }

        .candidate p {
            color: #718096;
            font-size: 13px;
            margin: 8px 0;
        }

        .release-count {
            font-size: 15px !important;
            color: #2d3748 !important;
            background: #edf2f7;
            padding: 8px;
            border-radius: 5px;
        }

        .release-count strong {
            color: #2b6cb0;
            font-size: 18px;
        }

        .results {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 1px 4px rgba(0,0,0,0.08);
        }

        .results-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 20px;
            flex-wrap: wrap;
            margin-bottom: 20px;
        }

        .results-header h2 {
            margin: 0;
        }

        .import-all-button {
            background: #38a169;
            font-size: 15px;
            font-weight: bold;
            padding: 11px 18px;
        }

        .import-all-button:hover {
            background: #2f855a;
        }

        .import-all-button:disabled {
            background: #a0aec0;
        }

        .summary {
            margin-bottom: 20px;
            color: #4a5568;
            line-height: 1.8;
        }

        .stats-box {
            background: #f7fafc;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 12px 15px;
            margin-bottom: 20px;
            display: flex;
            gap: 30px;
            flex-wrap: wrap;
        }

        .stat {
            display: flex;
            flex-direction: column;
        }

        .stat-label {
            color: #718096;
            font-size: 12px;
        }

        .stat-value {
            color: #2d3748;
            font-size: 20px;
            font-weight: bold;
        }

        .stat-highlight {
            color: #38a169;
        }

        .import-note {
            font-size: 12px;
            color: #718096;
            margin-top: 8px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            padding: 10px;
            border-bottom: 1px solid #e2e8f0;
            text-align: left;
            vertical-align: middle;
        }

        th {
            background: #edf2f7;
        }

        .album-cover {
            width: 60px;
            height: 60px;
            object-fit: cover;
            border-radius: 4px;
        }

        .harmony-button {
            display: inline-block;
            padding: 7px 10px;
            background: #38a169;
            color: white;
            text-decoration: none;
            border-radius: 4px;
            font-size: 13px;
        }

        .harmony-button:hover {
            background: #2f855a;
        }

        .spaced {
            font-family: monospace;
            font-size: 11px;
            color: #718096;
            word-break: break-all;
        }

        .history-link {
            display: inline-block;
            margin-top: 10px;
            font-size: 12px;
            color: #3182ce;
            text-decoration: none;
        }

        .history-link:hover {
            text-decoration: underline;
        }

    </style>

</head>

<body>

<div class="container">

    <h1>Auto-Stage Import Console</h1>

    <div class="search-box">

        <form method="POST" action="/search">

            <input
                type="text"
                name="artist_query"
                placeholder="Artist name or Deezer ID"
                value="{{ data.artist_query }}"
                required
            >

            <button type="submit">
                Search Artist
            </button>

        </form>

    </div>


    <div class="status">
        {{ data.status }}
    </div>


    <!-- LIFETIME IMPORT STATISTICS -->

    <div class="stats-box">

        <div class="stat">

            <span class="stat-label">
                Total Sent to MusicBrainz
            </span>

            <span class="stat-value stat-highlight">
                {{ import_stats.total_unique_sent }}
            </span>

        </div>

        <div class="stat">

            <span class="stat-label">
                Total Import Actions
            </span>

            <span class="stat-value">
                {{ import_stats.total_actions }}
            </span>

        </div>

    </div>


    <!-- LIVE SCAN OUTPUT -->

    <div
        id="scan-output"
        class="scan-output"
    >

        <div
            class="scan-output-header"
            style="
                position: sticky;
                top: 0;
                z-index: 10;
                background: white;
                padding: 8px 0;
                border-bottom: 1px solid #ddd;
            "
        >

            <span>Live Scan Output</span>

            <button
                id="cancel-scan-button"
                type="button"
                onclick="cancelScan()"
                style="
                    float: right;
                    background: #e53e3e;
                    color: white;
                    border: none;
                    padding: 6px 12px;
                    border-radius: 4px;
                    cursor: pointer;
                "
            >
                Cancel Analysis
            </button>
        </div>

        <div id="scan-output-text"></div>

    </div>


    <!-- ARTIST CANDIDATES -->

    {% if data.candidates %}

        <h2>Verify Artist</h2>

        <div class="candidate-grid">

            {% for candidate in data.candidates %}

                <div class="candidate">

                    {% if candidate.picture_medium %}

                        <img
                            src="{{ candidate.picture_medium }}"
                            alt="{{ candidate.name }}"
                        >

                    {% endif %}

                    <h3>
                        {{ candidate.name }}
                    </h3>

                    <p>
                        Deezer ID: {{ candidate.id }}
                    </p>

                    <p class="release-count">

                        Releases to scan:
                        <strong>
                            {{ candidate.release_count }}
                        </strong>

                    </p>

                    <form
                        method="POST"
                        action="/scan"
                    >

                        <input
                            type="hidden"
                            name="artist_id"
                            value="{{ candidate.id }}"
                        >

                        <input
                            type="hidden"
                            name="artist_name"
                            value="{{ candidate.name }}"
                        >

                        <input
                            type="hidden"
                            name="artist_query"
                            value="{{ data.artist_query }}"
                        >

                        <input
                            type="hidden"
                            name="expected_releases"
                            value="{{ candidate.release_count }}"
                        >

                        <button
                            type="submit"
                            {% if candidate.release_count == 0 %}
                                disabled
                            {% endif %}
                        >
                            Analyze This Artist
                        </button>

                    </form>

                </div>

            {% endfor %}

        </div>

    {% endif %}


    <!-- RESULTS -->

    {% if data.missing_items %}

        <div class="results">

            <div class="results-header">

                <h2>
                    Missing Releases
                </h2>

                <button
                    id="import-all-button"
                    class="import-all-button"
                    type="button"
                    onclick="importAll()"
                >
                    Auto-Stage All
                </button>

            </div>


            <div class="summary">

                Results for:
                <strong>{{ data.resolved_name }}</strong>

                (Deezer ID: {{ data.artist_id }})

                <br>

                Total Albums Retrieved:
                <strong>{{ data.albums_count }}</strong>

                |

                Albums Checked:
                <strong>{{ data.checked_count }}</strong>

                |

                Existing on MusicBrainz:
                <strong>{{ data.existing }}</strong>

                |

                Confirmed Missing:
                <strong>{{ data.missing_items|length }}</strong>

                |

                No UPC:
                <strong>{{ data.no_upc }}</strong>

                |

                Lookup Errors:
                <strong>{{ data.errors }}</strong>

            </div>


            <div class="import-note">

                Auto-Stage All will open each confirmed missing release
                in a separate browser tab.

                <br>

                The statistic below tracks releases sent through
                this tool. It does not confirm that the import was
                ultimately completed in MusicBrainz.

            </div>


            <table>

                <thead>

                    <tr>

                        <th>Cover</th>
                        <th>Album</th>
                        <th>UPC</th>
                        <th>Auto-Stage</th>
                        <th>Harmony URL</th>

                    </tr>

                </thead>

                <tbody>

                    {% for item in data.missing_items %}

                        <tr>

                            <td>

                                {% if item.cover %}

                                    <img
                                        class="album-cover"
                                        src="{{ item.cover }}"
                                        alt="{{ item.title }}"
                                    >

                                {% endif %}

                            </td>

                            <td>
                                {{ item.title }}
                            </td>

                            <td>
                                {{ item.upc }}
                            </td>

                            <td>

                                <a
                                    class="harmony-button"
                                    href="{{ item.harmony_link }}"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                >
                                    Auto-Stage
                                </a>

                            </td>

                            <td>

                                <span class="spaced">
                                    {{ item.display_url }}
                                </span>

                            </td>

                        </tr>

                    {% endfor %}

                </tbody>

            </table>

        </div>

    {% endif %}

</div>


<!-- IMPORT TRACKING + IMPORT ALL -->

<script>

    function importAll() {

        const button =
            document.getElementById(
                "import-all-button"
            );

        if (!button) {
            return;
        }


        const releases = [
            {% for item in data.missing_items %}
            {
                artistName:
                    {{ data.resolved_name|tojson }},

                artistId:
                    {{ data.artist_id|tojson }},

                albumId:
                    {{ item.album_id|tojson }},

                albumTitle:
                    {{ item.title|tojson }},

                upc:
                    {{ item.upc|tojson }},

                url:
                    {{ item.harmony_link|tojson }}
            }{% if not loop.last %},{% endif %}
            {% endfor %}
        ];


        if (releases.length === 0) {

            alert(
                "There are no missing releases to import."
            );

            return;
        }


        const confirmed =
            confirm(
                "Open " +
                releases.length +
                " missing releases in separate tabs?"
            );


        if (!confirmed) {
            return;
        }


        button.disabled = true;

        button.textContent =
            "Opening " +
            releases.length +
            " Imports...";


        let index = 0;


        function openNext() {

            if (index >= releases.length) {

                button.textContent =
                    "All Imports Opened";

                setTimeout(
                    function() {
                        window.location.reload();
                    },
                    1000
                );

                return;
            }


            const release =
                releases[index];


            const newWindow =
                window.open(
                    release.url,
                    "_blank"
                );

            index++;

            button.textContent =
                "Opening " +
                index +
                " / " +
                releases.length;


            setTimeout(
                openNext,
                150
            );
        }


        openNext();

    }

</script>


<!-- LIVE LOG POLLING -->

<script>

    function cancelScan() {

        const button =
            document.getElementById(
                "cancel-scan-button"
            );

        if (!button) {
            return;
        }


        const confirmed =
            confirm(
                "Cancel the current artist analysis?"
            );

        if (!confirmed) {
            return;
        }


        button.disabled = true;

        button.textContent =
            "Cancelling...";


        fetch(
            "/cancel-scan",
            {
                method: "POST"
            }
        )

            .then(
                response =>
                    response.json()
            )

            .then(
                data => {

                    if (!data.ok) {

                        alert(
                            data.error ||
                            "Unable to cancel the analysis."
                        );

                        button.disabled = false;

                        button.textContent =
                            "Cancel Analysis";

                        return;
                    }

                    button.textContent =
                        "Cancellation Requested";

                }
            )

            .catch(
                error => {

                    console.error(
                        "Cancel scan error:",
                        error
                    );

                    alert(
                        "Unable to contact the dashboard."
                    );

                    button.disabled = false;

                    button.textContent =
                        "Cancel Analysis";

                }
            );

    }


    let logTimer = null;

    /*
     * Tracks the previous running state.
     *
     * This allows us to detect the exact moment the
     * background scan changes from RUNNING to COMPLETE.
     */

    let previousRunningState = false;


    function pollScanLog() {

        fetch("/scan-log")

            .then(response => response.json())

            .then(data => {

                const output =
                    document.getElementById(
                        "scan-output"
                    );

                const outputText =
                    document.getElementById(
                        "scan-output-text"
                    );


                if (
                    data.running ||
                    data.log.length > 0
                ) {

                    output.style.display =
                        "block";

                    outputText.textContent =
                        data.log.join(
                            "\\n"
                        );

                    output.scrollTop =
                        output.scrollHeight;
                }


                /*
                 * Detect transition:
                 *
                 *     RUNNING -> COMPLETE
                 *
                 * This also handles:
                 *
                 *     RUNNING -> CANCELLED
                 */

                if (
                    previousRunningState === true &&
                    data.running === false
                ) {

                    if (logTimer !== null) {

                        clearTimeout(
                            logTimer
                        );

                        logTimer = null;
                    }

                    setTimeout(
                        function() {

                            window.location.reload();

                        },
                        250
                    );

                    return;
                }


                previousRunningState =
                    data.running;


                if (data.running) {

                    logTimer =
                        setTimeout(
                            pollScanLog,
                            500
                        );

                } else {

                    if (logTimer !== null) {

                        clearTimeout(
                            logTimer
                        );

                        logTimer = null;
                    }
                }

            })

            .catch(error => {

                console.error(
                    "Scan log error:",
                    error
                );

                logTimer =
                    setTimeout(
                        pollScanLog,
                        1000
                    );

            });

    }


    /*
     * Start polling when the page loads.
     *
     * This also means that if the page is refreshed while a
     * scan is running, the live output will reconnect.
     */

    pollScanLog();

</script>


</body>

</html>
"""


# ============================================================
# ROUTES
# ============================================================

@app.route("/")
def index():

    import_stats = get_import_stats()

    return render_template_string(
        HTML,
        data=current_data,
        import_stats=import_stats
    )


@app.route(
    "/search",
    methods=["POST"]
)
def search_artist():

    global current_data

    artist_query = request.form.get(
        "artist_query",
        ""
    ).strip()

    if not artist_query:

        return redirect("/")


    # Numeric Deezer ID

    if artist_query.isdigit():

        artist_id = artist_query

        albums = get_deezer_albums(
            artist_id
        )

        release_count = len(
            albums
        )

        current_data = {
            "artist_query": artist_query,
            "resolved_name": (
                f"Deezer ID {artist_id}"
            ),
            "artist_id": artist_id,
            "albums_count": 0,
            "checked_count": 0,
            "existing": 0,
            "errors": 0,
            "no_upc": 0,
            "missing_items": [],
            "status": (
                f"Ready to analyze Deezer "
                f"artist ID {artist_id}. "
                f"Found {release_count} "
                f"releases to scan."
            ),
            "candidates": [{
                "id": artist_id,
                "name": (
                    f"Deezer ID {artist_id}"
                ),
                "picture_medium": "",
                "release_count": release_count
            }]
        }

        return redirect("/")


    # Artist name search

    candidates = search_deezer_artists(
        artist_query
    )

    if not candidates:

        current_data = {
            "artist_query": artist_query,
            "resolved_name": None,
            "artist_id": "",
            "albums_count": 0,
            "checked_count": 0,
            "existing": 0,
            "errors": 0,
            "no_upc": 0,
            "missing_items": [],
            "status": (
                f'Error: No results matching '
                f'"{artist_query}" discovered '
                f"on Deezer."
            ),
            "candidates": []
        }

        return redirect("/")


    # Enrich each candidate with the exact release count
    # that the eventual scan will retrieve.
    enriched_candidates = []

    for candidate in candidates:

        candidate_copy = dict(
            candidate
        )

        candidate_id = candidate_copy.get(
            "id"
        )

        if candidate_id:

            candidate_albums = get_deezer_albums(
                candidate_id
            )

            candidate_copy["release_count"] = len(
                candidate_albums
            )

        else:

            candidate_copy["release_count"] = 0

        enriched_candidates.append(
            candidate_copy
        )


    current_data = {
        "artist_query": artist_query,
        "resolved_name": None,
        "artist_id": "",
        "albums_count": 0,
        "checked_count": 0,
        "existing": 0,
        "errors": 0,
        "no_upc": 0,
        "missing_items": [],
        "status": (
            f"Found {len(enriched_candidates)} "
            f"match suggestions. "
            f"Release counts loaded. "
            f"Please verify profile card choice."
        ),
        "candidates": enriched_candidates
    }

    return redirect("/")


@app.route(
    "/scan",
    methods=["POST"]
)
def run_scan():

    global current_data

    artist_id = request.form.get(
        "artist_id",
        ""
    ).strip()

    artist_name = request.form.get(
        "artist_name",
        f"ID: {artist_id}"
    ).strip()

    artist_query = request.form.get(
        "artist_query",
        artist_name
    ).strip()

    expected_releases_raw = request.form.get(
        "expected_releases",
        ""
    ).strip()


    if not artist_id:

        return redirect("/")


    # Prevent multiple simultaneous scans.

    if is_scan_running():

        current_data["status"] = (
            "A scan is already running. "
            "Please wait for it to finish."
        )

        return redirect("/")


    try:

        expected_releases = int(
            expected_releases_raw
        )

    except (TypeError, ValueError):

        expected_releases = None


    # Reset the display immediately.

    clear_scan_log()
    reset_scan_import_counter()
    reset_scan_cancel()

    current_data = {
        "artist_query": artist_query,
        "resolved_name": artist_name,
        "artist_id": artist_id,
        "albums_count": 0,
        "checked_count": 0,
        "existing": 0,
        "errors": 0,
        "no_upc": 0,
        "missing_items": [],
        "status": (
            f'Starting analysis of '
            f'"{artist_name}"...'
        ),
        "candidates": []
    }


    # Start background scan.

    scan_thread = threading.Thread(
        target=perform_scan,
        args=(
            artist_id,
            artist_name,
            artist_query,
            expected_releases
        ),
        daemon=True
    )

    scan_thread.start()

    return redirect("/")


@app.route(
    "/cancel-scan",
    methods=["POST"]
)
def cancel_scan():

    if not is_scan_running():

        return jsonify({
            "ok": False,
            "error": "No artist analysis is currently running."
        }), 409

    request_scan_cancel()

    add_scan_log("")

    add_scan_log(
        "Cancellation requested. "
        "The current request will finish, then the scan will stop."
    )

    return jsonify({
        "ok": True,
        "status": "cancellation_requested"
    })


@app.route("/clear-results")
def clear_results():
    """
    Clear the persisted last scan and reset the dashboard.
    """

    global current_data

    clear_last_scan()

    current_data = {
        "artist_query": "",
        "resolved_name": "",
        "artist_id": "",
        "albums_count": 0,
        "checked_count": 0,
        "existing": 0,
        "errors": 0,
        "no_upc": 0,
        "missing_items": [],
        "status": "Results cleared. Enter an Artist Name or ID number to search.",
        "candidates": []
    }

    clear_scan_log()
    reset_scan_import_counter()
    reset_scan_cancel()

    return redirect("/")


@app.route("/mb-seed")
def mb_seed_route():

    deezer_url = request.args.get(
        "url",
        ""
    ).strip()

    if not deezer_url:
        return (
            "<h1>Missing Deezer URL</h1>"
            "<p>No Deezer release URL was supplied.</p>",
            400,
        )

    html, status, error = create_auto_stage_seed(
        deezer_url
    )

    if error:
        return f"""
        <!doctype html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Auto-Stage Error</title>
            <style>
                body {{
                    font-family: system-ui, sans-serif;
                    max-width: 760px;
                    margin: 60px auto;
                    padding: 0 20px;
                    line-height: 1.5;
                }}
                .error {{
                    border: 1px solid #c00;
                    border-radius: 10px;
                    padding: 24px;
                }}
                a {{
                    display: inline-block;
                    margin-top: 20px;
                }}
            </style>
        </head>
        <body>
            <div class="error">
                <h1>Auto-Stage Stopped</h1>
                <p>{escape(str(error))}</p>
                <a href="/">Return to dashboard</a>
            </div>
        </body>
        </html>
        """, status

    return html, status, {
        "Content-Type": "text/html; charset=utf-8"
    }


@app.route("/import-stats")
def import_stats():

    stats = get_import_stats()

    return jsonify({
        "total_unique_sent":
            stats["total_unique_sent"],

        "total_actions":
            stats["total_actions"],

        "imports":
            stats["imports"]
    })


@app.route("/scan-log")
def get_scan_log():

    with scan_lock:

        return {
            "running": scan_running,
            "log": list(scan_log)
        }


# ============================================================
# HARMONY RELEASE COMPLETION
# ============================================================

HARMONY_COMPLETIONS_FILE = "/opt/mb-automation/harmony_completions.json"
harmony_completion_lock = threading.Lock()


def get_harmony_completions():

    if not os.path.exists(HARMONY_COMPLETIONS_FILE):
        return []

    try:

        with open(
            HARMONY_COMPLETIONS_FILE,
            "r"
        ) as f:

            data = json.load(f)

        if isinstance(data, list):
            return data

    except Exception as error:

        print(
            f"WARNING: Could not read Harmony completion state: {error}"
        )

    return []


def save_harmony_completions(completions):

    temp_file = (
        HARMONY_COMPLETIONS_FILE +
        ".tmp"
    )

    with open(
        temp_file,
        "w"
    ) as f:

        json.dump(
            completions,
            f,
            indent=2,
        )

    os.replace(
        temp_file,
        HARMONY_COMPLETIONS_FILE,
    )


@app.route(
    "/harmony-release-jobs",
    methods=["GET"]
)
def harmony_release_jobs():

    with harmony_completion_lock:

        completions = get_harmony_completions()

    return jsonify({
        "ok": True,
        "jobs": completions,
    })


@app.route(
    "/harmony-release-job/claim",
    methods=["POST"]
)
def harmony_release_job_claim():

    data = request.get_json(
        silent=True
    ) or {}

    release_mbid = str(
        data.get(
            "release_mbid",
            ""
        )
    ).strip()

    if not release_mbid:

        return jsonify({
            "ok": False,
            "error": "Missing release_mbid",
        }), 400

    if not re.fullmatch(
        r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        release_mbid,
    ):

        return jsonify({
            "ok": False,
            "error": "Invalid release_mbid",
        }), 400

    with harmony_completion_lock:

        completions = get_harmony_completions()

        existing = next(
            (
                item
                for item in completions
                if item.get("release_mbid") == release_mbid
            ),
            None,
        )

        if not existing:

            return jsonify({
                "ok": False,
                "error": "Release job not found",
            }), 404

        current_status = str(
            existing.get(
                "status",
                ""
            )
        ).strip()

        if current_status != "artwork_ready":

            return jsonify({
                "ok": True,
                "claimed": False,
                "release_mbid": release_mbid,
                "status": current_status,
            })

        existing["status"] = "running"

        existing["started_at"] = (
            datetime.now().isoformat(
                timespec="seconds"
            )
        )

        save_harmony_completions(
            completions
        )

    print(
        "Harmony release job claimed: "
        f"{release_mbid}"
    )

    return jsonify({
        "ok": True,
        "claimed": True,
        "release_mbid": release_mbid,
        "status": "running",
    })


@app.route(
    "/harmony-release-job/complete",
    methods=["POST"]
)
def harmony_release_job_complete():

    data = request.get_json(
        silent=True
    ) or {}

    release_mbid = str(
        data.get(
            "release_mbid",
            ""
        )
    ).strip()

    status = str(
        data.get(
            "status",
            ""
        )
    ).strip()

    error = str(
        data.get(
            "error",
            ""
        )
    ).strip()

    if not release_mbid:

        return jsonify({
            "ok": False,
            "error": "Missing release_mbid",
        }), 400

    if not re.fullmatch(
        r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        release_mbid,
    ):

        return jsonify({
            "ok": False,
            "error": "Invalid release_mbid",
        }), 400

    if status not in {
        "completed",
        "failed",
    }:

        return jsonify({
            "ok": False,
            "error": "Invalid status",
        }), 400

    with harmony_completion_lock:

        completions = get_harmony_completions()

        existing = next(
            (
                item
                for item in completions
                if item.get("release_mbid") == release_mbid
            ),
            None,
        )

        if not existing:

            return jsonify({
                "ok": False,
                "error": "Release job not found",
            }), 404

        current_status = str(
            existing.get(
                "status",
                ""
            )
        ).strip()

        if current_status != "running":

            return jsonify({
                "ok": True,
                "updated": False,
                "release_mbid": release_mbid,
                "status": current_status,
            })

        existing["status"] = status

        existing["completed_at"] = (
            datetime.now().isoformat(
                timespec="seconds"
            )
        )

        if status == "failed":

            existing["error"] = (
                error or
                "Artwork processing failed."
            )

        else:

            existing.pop(
                "error",
                None
            )

        save_harmony_completions(
            completions
        )

    print(
        "Harmony release job "
        f"{status}: {release_mbid}"
    )

    return jsonify({
        "ok": True,
        "updated": True,
        "release_mbid": release_mbid,
        "status": status,
    })


@app.route(
    "/harmony-release-complete",
    methods=["POST"]
)
def harmony_release_complete():

    data = request.get_json(
        silent=True
    ) or {}

    release_mbid = str(
        data.get(
            "release_mbid",
            ""
        )
    ).strip()

    deezer = str(
        data.get(
            "deezer",
            ""
        )
    ).strip()

    gtin = str(
        data.get(
            "gtin",
            ""
        )
    ).strip()

    artwork = data.get(
        "artwork"
    )

    if not release_mbid:

        return jsonify({
            "ok": False,
            "error": "Missing release_mbid",
        }), 400

    if not re.fullmatch(
        r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}",
        release_mbid,
    ):

        return jsonify({
            "ok": False,
            "error": "Invalid release_mbid",
        }), 400

    if artwork is not None and not isinstance(
        artwork,
        list
    ):

        return jsonify({
            "ok": False,
            "error": "Invalid artwork payload",
        }), 400

    with harmony_completion_lock:

        completions = get_harmony_completions()

        existing = next(
            (
                item
                for item in completions
                if item.get("release_mbid") == release_mbid
            ),
            None,
        )

        # ----------------------------------------------------
        # ARTWORK NOTIFICATION
        # ----------------------------------------------------
        if isinstance(
            artwork,
            list
        ):

            if existing:

                existing["deezer"] = (
                    deezer or
                    existing.get(
                        "deezer",
                        ""
                    )
                )

                existing["gtin"] = (
                    gtin or
                    existing.get(
                        "gtin",
                        ""
                    )
                )

                existing["artwork"] = artwork

                current_status = str(
                    existing.get(
                        "status",
                        ""
                    )
                ).strip()

                if current_status in {
                    "detected",
                    "waiting_for_artwork",
                }:

                    existing["status"] = (
                        "artwork_ready"
                    )

                    existing["artwork_ready_at"] = (
                        datetime.now().isoformat(
                            timespec="seconds"
                        )
                    )

                save_harmony_completions(
                    completions
                )

                print()
                print("========================================")
                print("HARMONY ARTWORK RECEIVED")
                print("========================================")
                print(
                    f"Release MBID: {release_mbid}"
                )
                print(
                    f"Artwork items: {len(artwork)}"
                )
                print(
                    f"Status:       "
                    f"{existing.get('status', '')}"
                )
                print("========================================")
                print()

                return jsonify({
                    "ok": True,
                    "duplicate": False,
                    "artwork_received": True,
                    "release_mbid": release_mbid,
                    "artwork_count": len(artwork),
                    "status": existing.get(
                        "status",
                        ""
                    ),
                })

            # Artwork arrived before the initial notification.
            completion = {
                "release_mbid": release_mbid,
                "deezer": deezer,
                "gtin": gtin,
                "artwork": artwork,
                "status": "artwork_ready",
                "detected_at": datetime.now().isoformat(
                    timespec="seconds"
                ),
                "artwork_ready_at": datetime.now().isoformat(
                    timespec="seconds"
                ),
            }

            completions.append(
                completion
            )

            save_harmony_completions(
                completions
            )

            print()
            print("========================================")
            print("HARMONY ARTWORK RECEIVED")
            print("========================================")
            print(
                f"Release MBID: {release_mbid}"
            )
            print(
                f"Artwork items: {len(artwork)}"
            )
            print(
                "Status:       artwork_ready"
            )
            print("========================================")
            print()

            return jsonify({
                "ok": True,
                "duplicate": False,
                "artwork_received": True,
                "release_mbid": release_mbid,
                "artwork_count": len(artwork),
                "status": "artwork_ready",
            })

        # ----------------------------------------------------
        # INITIAL RELEASE COMPLETION NOTIFICATION
        # ----------------------------------------------------
        if existing:

            print(
                "Harmony release completion already recorded: "
                f"{release_mbid}"
            )

            return jsonify({
                "ok": True,
                "duplicate": True,
                "release_mbid": release_mbid,
                "status": existing.get(
                    "status",
                    ""
                ),
            })

        completion = {
            "release_mbid": release_mbid,
            "deezer": deezer,
            "gtin": gtin,
            "status": "detected",
            "detected_at": datetime.now().isoformat(
                timespec="seconds"
            ),
        }

        completions.append(
            completion
        )

        save_harmony_completions(
            completions
        )

    print()
    print("========================================")
    print("HARMONY RELEASE COMPLETION DETECTED")
    print("========================================")
    print(
        f"Release MBID: {release_mbid}"
    )
    print(
        f"Deezer:       {deezer}"
    )
    print(
        f"GTIN:         {gtin}"
    )
    print(
        "Status:       detected"
    )
    print("========================================")
    print()

    return jsonify({
        "ok": True,
        "duplicate": False,
        "release_mbid": release_mbid,
        "status": "detected",
    })


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    app.run(
        host="0.0.0.0",
        port=8080,
        debug=False
    )